### PR TITLE
add Client.delete() and Client.put()

### LINKED ISSUE #11: Add put and delete api methods
They are useful to interact with other services, i.e. workout-service among others

### PR DESCRIPTION
**Pull request by matin**
Add `Client.delete()` and `Client.put()`

Closes #11

### CODE REVIEW

**Comment by matin** [comment]
@OscarSalgado could you add `Client.put()` along with it's test?

**Comment by OscarSalgado** [comment]
You can cherry pick 467a057038b5200ff36b17b1d9845353514cfea3

Please make any necessary change

**Comment by matin** [comment]
@OscarSalgado can you add the recorded VCR cassette?

To run the tests, you need to first make sure you have a saved, active tokens located in $GARTH_HOME.

**Comment by OscarSalgado** [comment]
Now it should be ok ac73b450b0fe1446be12761497290d069393063a

**Comment by matin** [comment]
Looks good. Thanks!

**Pull request merged**
