### PR TITLE
Fix values as nullable

### PR DESCRIPTION
**Pull request by sdenel**
Some values can in fact be None in certain circumstances, like when changing from one watch to another

### CODE REVIEW

**Comment by matin** [comment]
Looks good. I'll merge and release tomorrow

**Comment by duarteocarmo** [comment]
@matin, also sleep can be null. (e.g., charging my watch while sleeping)

image


image

**Comment by duarteocarmo** [comment]
Perhaps we can include that here as well? I think and Optional in stats/sleep should be enough!

**Comment by matin** [comment]
Released as [0.4.45](https://github.com/matin/garth/releases/tag/0.4.45)

@duarteocarmo included your request as well

**Pull request merged**
